# Robot Configuration Parameters
TrajectoryPlannerROS:
    acc_lim_x: 1.00
    acc_lim_y: 1.00
    acc_lim_th: 1.2
    max_vel_x: 0.3
    min_vel_x: 0.1
    max_rotational_vel: 0.5
    min_in_place_rotational_vel: 0.1
    escape_vel: -0.1
    holonomic_robot: true

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.3
    #yaw_goal_tolerance: 0.2
    yaw_goal_tolerance: 3.0

    # Forward Simulation Parameters
    sim_time: 1.7
    sim_granularity: 0.025
    vx_samples: 3
    vtheta_samples: 6

    # Trajectory Scoring Parameters
    # goal_distance_bias: 0.8
    # path_distance_bias: 0.6
    # occdist_scale: 0.01
    goal_distance_bias: 0.3
    path_distance_bias: 0.01
    occdist_scale: 0.9
    heading_lookahead: 0.325
    dwa: true
    publish_cost_grid_pc: false

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.01

